camera_name: 'camera'
camera_namespace: 'camera'
serial_no: ''
usb_port_id: ''
device_type: 'D435i'
config_file: ''
json_file_path: ''
initial_reset: true
accelerate_gpu_with_glsl: false
rosbag_filename: ''
log_level: 'info'
output: 'screen'
enable_color: true
rgb_camera:
  color_profile: '424,240,15'
  color_format: 'RGB8'
  enable_auto_exposure: true
enable_depth: true
enable_infra: false
enable_infra1: false
enable_infra2: false
depth_module:
  depth_profile: '424,240,15'
  depth_format: 'Z16'
  infra_profile: '0,0,0'
  infra_format: 'RGB8'
  infra1_format: 'Y8'
  infra2_format: 'Y8'
  exposure: 8500
  gain: 16
  hdr_enabled: false
  enable_auto_exposure: true
  exposure_1: 7500
  gain_1: 16
  exposure_2: 1
  gain_2: 16
enable_sync: false
enable_rgbd: false
enable_gyro: false
enable_accel: false
gyro_fps: 0
accel_fps: 0
unite_imu_method: 0  # [0-None, 1-copy, 2-linear_interpolation]
clip_distance: -2.0
angular_velocity_cov: 0.01
linear_accel_cov: 0.01
diagnostics_period: 0.0
publish_tf: true
tf_publish_rate: 0.0
pointcloud:
  enable: true
  stream_filter: 2
  stream_index_filter: 0
  ordered_pc: true
  allow_no_texture_points: true
align_depth:
  enable: true
colorizer:
  enable: false
decimation_filter:
  enable: false
spatial_filter:
  enable: false
temporal_filter:
  enable: false
disparity_filter:
  enable: false
hole_filling_filter:
  enable: false
hdr_merge:
  enable: false
wait_for_device_timeout: -1.0
reconnect_timeout: 6.0
